[package]
name = "day03"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
#rustls = { version = "0.23.27", default-features = false, features = ["std"] }
webpki-roots = "1"
tokio-rustls = "0.26.2"
